### ISSUE TITLE
Moving js2-refactor under `js-emacs`

### ISSUE THREAD

**Issue by NicolasPetton** [js-emacs/js2-refactor.el#130]
Hi!

I think it would make sense to move js2-refactor to a new org in GitHub,
similar to https://github.com/clojure-emacs.

I created the https://github.com/js-emacs org some time ago with the purpose of moving
some of my projects there:

- Indium https://github.com/NicolasPetton/Indium
- xref-js2 https://github.com/NicolasPetton/xref-js2

I think js2-refactor would belong in the same category, and IMO it would
make sense to move it there as well.

@magnars already agreed to move this project under js-emacs, and the steps as I see them would be:

1. Setup js-emacs so that maintainers have access to the org
2. Move the repositories under js-emacs
3. Update the MELPA recipes

@magnars @nbfalcon ping.

**Comment by magnars** [comment]
Sounds good to me 👍

**Comment by NicolasPetton** [comment]
@magnars I've setup the `js-emacs` org and invited you both. As soon at the repo is transferred, I'll open a PR on MELPA to update the recipe.

**Comment by NicolasPetton** [comment]
I already moved `xref-js2`: https://github.com/js-emacs/xref-js2 and opened a PR for updating the MELPA recipe: https://github.com/melpa/melpa/pull/7471.

**Comment by magnars** [comment]
Done!

**Comment by NicolasPetton** [comment]
Awesome!

I've opened a PR to update the MELPA recipe here https://github.com/melpa/melpa/pull/7472.

Closing this issue.
